# Generated by Django 6.0 on 2025-12-05 04:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor', models.CharField(default='#0066FF', help_text='Cor em hexadecimal', max_length=7)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(help_text='Descrição curta da ideia')),
                ('conteudo', models.TextField(help_text='Conteúdo detalhado (HTML do TinyMCE)')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem de capa (máx 5MB)', null=True, upload_to='ideas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20)),
                ('data_agendada', models.DateTimeField(blank=True, help_text='Data e hora da apresentação', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apresentador', models.ForeignKey(blank=True, help_text='Quem vai apresentar esta ideia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideias_apresentando', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideias_criadas', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='ideias', to='talks.tag')),
            ],
            options={
                'verbose_name': 'Ideia',
                'verbose_name_plural': 'Ideias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='talks.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Comentário pai (para respostas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='talks.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='talks.idea')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['idea', 'created_at'], name='talks_comme_idea_id_0e0480_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('voto', 'Novo Voto'), ('voluntario', 'Novo Voluntário'), ('agendamento', 'Apresentação Agendada'), ('comentario', 'Novo Comentário'), ('mencao', 'Menção')], max_length=20)),
                ('mensagem', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='talks.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'lido'], name='talks_notif_user_id_94b325_idx'), models.Index(fields=['-created_at'], name='talks_notif_created_02cd1a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['-created_at'], name='talks_idea_created_793315_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['status'], name='talks_idea_status_702d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['data_agendada'], name='talks_idea_data_ag_d0fdad_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'idea'], name='talks_vote_user_id_615768_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'idea')},
        ),
    ]
