# Generated by Django 6.0 on 2025-12-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_remove_cancelado_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='idea',
            name='talks_idea_status_702d6d_idx',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='status',
        ),
    ]
