# Generated by Django 6.0 on 2025-12-13 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_remove_idea_talks_idea_status_702d6d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do template (ex: 'Start/Stop/Continue')", max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do template')),
                ('categorias', models.JSONField(help_text='Lista de categorias do template. Cada categoria deve ter: name (nome), slug (identificador), icon (emoji/ícone), color (cor hex). Ex: [{"name": "What went well", "slug": "went_well", "icon": "😊", "color": "#10b981"}]')),
                ('is_default', models.BooleanField(default=False, help_text='Se este é o template padrão ao criar novas retros')),
                ('is_system', models.BooleanField(default=False, help_text='Templates do sistema não podem ser editados/deletados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Retrospectiva',
                'verbose_name_plural': 'Templates de Retrospectiva',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Retro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título da retrospectiva (ex: 'Retro Sprint 15')", max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da retrospectiva')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da retrospectiva')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='rascunho', help_text='Status atual da retrospectiva', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(help_text='Usuário que criou a retrospectiva', on_delete=django.db.models.deletion.CASCADE, related_name='retros_criadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, help_text='Usuários que participaram da retrospectiva', related_name='retros_participadas', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Template utilizado (define as categorias de itens)', on_delete=django.db.models.deletion.PROTECT, related_name='retros', to='talks.retrotemplate')),
            ],
            options={
                'verbose_name': 'Retrospectiva',
                'verbose_name_plural': 'Retrospectivas',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text="Slug da categoria (ex: 'went_well', 'to_improve', 'action_items')", max_length=50)),
                ('conteudo', models.TextField(help_text='Conteúdo do item (texto do card)')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição dentro da categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(help_text='Usuário que criou este item', on_delete=django.db.models.deletion.CASCADE, related_name='retro_items', to=settings.AUTH_USER_MODEL)),
                ('retro', models.ForeignKey(help_text='Retrospectiva à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='talks.retro')),
                ('votes', models.ManyToManyField(blank=True, help_text='Usuários que votaram neste item', related_name='retro_items_votados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Retrospectiva',
                'verbose_name_plural': 'Itens de Retrospectiva',
                'ordering': ['categoria', '-votes__id', 'ordem', '-created_at'],
                'indexes': [models.Index(fields=['retro', 'categoria'], name='talks_retro_retro_i_40caf7_idx'), models.Index(fields=['autor'], name='talks_retro_autor_i_6243b9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='retro',
            index=models.Index(fields=['-data'], name='talks_retro_data_8053de_idx'),
        ),
        migrations.AddIndex(
            model_name='retro',
            index=models.Index(fields=['status'], name='talks_retro_status_255554_idx'),
        ),
        migrations.AddIndex(
            model_name='retro',
            index=models.Index(fields=['autor'], name='talks_retro_autor_i_332a82_idx'),
        ),
    ]
