# Generated by Django 6.0 on 2025-12-13 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_enabled', models.BooleanField(default=True, help_text='Habilita/desabilita o módulo Chapter (ideias/apresentações)', verbose_name='Chapter Habilitado')),
                ('retro_enabled', models.BooleanField(default=False, help_text='Habilita/desabilita o módulo Retro (retrospectivas)', verbose_name='Retro Habilitado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'system_configuration',
            },
        ),
    ]
