# Generated by Django 6.0 on 2025-12-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='retro_enabled',
            field=models.BooleanField(default=True, help_text='Habilita/desabilita o módulo Retro (retrospectivas)', verbose_name='Retro Habilitado'),
        ),
    ]
